
final Map<String, List<String>> productImagesByName = {
  'Floral Summer Dress': ['1.jpg', '2.jpg', '4.jpg'],
  'Classic Denim Jacket': ['2.jpg'],
  'Leather Crossbody Bag': ['4.jpg'],
  'White Sneakers': ['21.jpg'],
  'Satin Blouse': ['8.jpg'],
  'Ankle Boots': ['Ankle Boots.jpg','Ankle Boots1.jpg','Ankle Boots2.jpg','Ankle Boots3.jpg'],
  'Slim Fit Chinos': ['11.jpg'],
  'Men Outfit': ['13.jpg'],
  'Kids Collection': ['15.jpg'],
  'Casual V-Neck T-Shirt': ['22.jpg'],
  'High Waist Leggings': ['23.jpg'],
  'Lightweight Flat Sandals': ['24.jpg'],
  'Basic Cotton T-Shirt': ['25.jpg'],
  'Lightweight Windbreaker': ['26.jpg'],
  'Sports Cap': ['27.jpg'],

  'Floral Maxi Dress': ['Floral Maxi Dress.jpg'],
  'Casual Polo Shirt': ['Casual Polo Shirt.jpg'],
  'Graphic T-Shirt': ['Graphic T-Shirt1.jpg','Graphic T-Shirt.jpg','Graphic T-Shirt2.jpg'],
  'Wool Scarf': ['Wool Scarf.jpg','Wool Scarf1.jpg','Wool Scarf2.jpg',],
  'Running Shoes': ['Running Shoes.jpg'],
  'Leather Handbag': ['Leather Handbag.jpg','Leather Handbag1.jpg','Leather Handbag2.jpg','Leather Handbag3.jpg',],
  'Winter Coat': ['Winter Coat.jpg','Winter Coat1.jpg','Winter Coat2.jpg'],
  'Sneakers': ['Sneakers.jpg','Sneakers1.jpg','Sneakers2.jpg'],
  'Chiffon Blouse': ['Chiffon Blouse1.jpg','Chiffon Blouse2.jpg','Chiffon Blouse3.jpg'],
  'Leather Belt': ['Leather Belt.jpg'],
  'Denim Overalls': ['Denim Overalls.jpg'],
  'Leather Loafers': ['Leather Loafers.jpg','Leather Loafers1.jpg','Leather Loafers2.jpg'],
  'Baseball Cap': ['Baseball Cap.jpg'],
  'Pleated Skirt': ['Pleated Skirt.jpg','Pleated Skirt1.jpg','Pleated Skirt2.jpg',],
  'Graphic Hoodie': ['Graphic Hoodie.jpg'],
  'Rain Jacket': ['Rain Jacket.jpg','1Rain Jacket.jpg','Rain Jacket1.jpg'],
  'Winter Boots': ['Winter Boots.jpg'],
  'Leather Gloves': ['Leather Gloves.jpg'],
  'Knitted Sweater': ['Knitted Sweater.jpg'],
  'Chino Shorts': ['Chino Shorts.jpg'],
  'Cotton Pajamas': ['Cotton Pajamas.jpg','Cotton Pajamas1.jpg','Cotton Pajamas2.jpg',],
  'Sandals': ['sandals.jpg'],
};



    final imageMap = {
      'Floral Summer Dress': 'assets/images/1.jpg',
      'Classic Denim Jacket': 'assets/images/2.jpg',
      'Leather Crossbody Bag': 'assets/images/4.jpg',
      'White Sneakers': 'assets/images/21.jpg',
      'Satin Blouse': 'assets/images/8.jpg',
      'Ankle Boots': 'assets/images/14.jpg',
      'Slim Fit Chinos': 'assets/images/11.jpg',
      'Men Outfit': 'assets/images/13.jpg',
      'Kids Collection': 'assets/images/15.jpg',
      'Casual V-Neck T-Shirt':'assets/images/22.jpg',
      'High Waist Leggings': 'assets/images/23.jpg',
      'Lightweight Flat Sandals': 'assets/images/24.jpg',
      'Basic Cotton T-Shirt': 'assets/images/25.jpg',
      '	Lightweight Windbreaker':'assets/images/26.jpg',
      'Sports Cap':'assets/images/27.jpg',
      'Floral Maxi Dress': 'assets/images/Floral Maxi Dress.jpg',
      'Casual Polo Shirt': 'assets/images/Casual Polo Shirt.jpg',
      'Graphic T-Shirt': 'assets/images/Graphic T-Shirt1.jpg',
      'Wool Scarf': 'assets/images/Wool Scarf.jpg',
      'Running Shoes': 'assets/images/Running Shoes.jpg',
      'Leather Handbag': 'assets/images/Leather Handbag.jpg',
      'Winter Coat': 'assets/images/Winter Coat.jpg',
      'Sneakers': 'assets/images/Sneakers.jpg',
      'Chiffon Blouse': 'assets/images/Chiffon Blouse1.jpg',
      'Leather Belt':'assets/images/Leather Belt.jpg',
      'Denim Overalls': 'assets/images/Denim Overalls.jpg',
      'Leather Loafers': 'assets/images/Leather Loafers.jpg',
      'Baseball Cap': 'assets/images/Baseball Cap.jpg',
      'Pleated Skirt':'assets/images/Pleated Skirt.jpg',
      'Graphic Hoodie':'assets/images/Graphic Hoodie.jpg',
      'Rain Jacket': 'assets/images/1Rain Jacket.jpg',
      'Winter Boots': 'assets/images/Winter Boots.jpg',
      'Leather Gloves': 'assets/images/Leather Gloves.jpg',
      'Knitted Sweater':'assets/images/Knitted Sweater.jpg',
      'Chino Shorts':'assets/images/Chino Shorts.jpg',
      'Cotton Pajamas': 'assets/images/Cotton Pajamas.jpg',
      'Sandals': 'assets/images/sandals.jpg',
    };

